# Generated by Django 2.2.7 on 2019-11-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('pro1', models.CharField(max_length=30)),
                ('pro2', models.CharField(max_length=30)),
                ('pro3', models.CharField(max_length=30)),
            ],
        ),
    ]
